### ISSUE TITLE
نحوه استفاده رو هم بنویس لطفا

### ISSUE THREAD

**Issue by alian93710** [tiampersian/kendo-jalali-date-inputs#1]

**Comment by tiampersian** [comment]
https://github.com/tiampersian/kendo-jalali-date-inputs
تو صفحه اصلی هست که ...
البته بگم این پکیج برای کندو نوشته شده
https://www.telerik.com/kendo-angular-ui/components/
پکیج @progress/kendo-theme-default  رو خودتون باید نصب کنید

**Comment by MostafaSaadatnia** [comment]
این پکیج تنها پکیج فارسی کندو هست لطفا برای نسخه های جدید تر انگولار و کندو هم آپدیت بذارید همین الان من چندین روزه درگیرم.لطفا یک داکیومنتیشن مناسب بذارید من داوطلب هستم که این کارا رو انجام بدیم و کمی نسخه رو بهینه تر بکنیم.

**Comment by tiampersian** [comment]
این پکیج بروز هست
الان با آخرین ورژن انگولار مطابقت داره
 در مورد داکیومنت پکیج ،این پکیج در اصل یک سری override  روی پکیج اصلی کندو
انجام میده ولی در ادامه شما از کامپوونت اصلی کندو استفاده میکنید
مستندات کندو
https://www.telerik.com/kendo-angular-ui/components/dateinputs/
شما پکیج فارسی رو نصب کنید و import کنید ، بقیه چیزا عینا مستندات کندو هست

**Comment by tiampersian** [comment]
شما بجای


import { DateInputsModule } from ***@***.***/kendo-angular-dateinputs";


از

import { KendoJalaliDateInputsModule } from
> ***@***.***/kendo-jalali-date-inputs';


استفاده کنید .
جهت استفاده از کامپوننت ها ، عینا از مستندات خود کندو استفاده کنید.
