### ISSUE TITLE
Conflict and Doesn't work with kendo version 14 

### ISSUE THREAD

**Issue by MostafaSaadatnia** [tiampersian/kendo-jalali-date-inputs#3]
Conflict and Doesn't work with kendo version 14

**Comment by tiampersian** [comment]
از ورژن های قدیمی استفاده کن فعلا 0.1.330
از ورژن 0.1.330 به بعد نسخه انگولار تغییر میکند
اگر مشکلی با بروزرسانی پروژتون دارید ، میتونی از ورژن های قدیمی یک branch
جدید بگیری و خودتون ادامه ش بدید.
فایل الصاقی پروژه یی با انگولار 14 هست که کار میکنه

 ng14.rar
<https://drive.google.com/file/d/1BUESK0KtFmDshs5WiiUefmAuxiTu43UP/view?usp=drive_web>
